[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_SERVER_BACKEND_URL = "https://secret-bridie-drivertc-bbe7d7d5.koyeb.app"
  REACT_APP_CLIENT_BACKEND_URL = "http://localhost:8001"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
