version: '3.8'

services:
  server-backend:
    build: ./server-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - drivertc-network

  client-backend:
    build: ./client-backend
    ports:
      - "8001:8001"
    environment:
      - SERVER_URL=ws://server-backend:8000
      - PORT=8001
    volumes:
      - ./shared-files:/app/shared
    networks:
      - drivertc-network
    depends_on:
      - server-backend

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_CLIENT_BACKEND_URL=http://localhost:8001
    networks:
      - drivertc-network
    depends_on:
      - client-backend

networks:
  drivertc-network:
    driver: bridge

volumes:
  shared-files:
